<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.1 - Importations des librairies</h3>
</div>

In [1]:
import pandas as pd

import numpy as np

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.2 - Chargement des fichiers</h3>
</div>

In [2]:
dispo = pd.read_csv('../Ressources/DisponibiliteAlimentaire_2017.csv')

politique = pd.read_csv('../Ressources/Stabilité.csv')

economique = pd.read_csv('../Ressources/PIB_par_habitant.csv')

social_1 = pd.read_csv('../Ressources/Population.csv')

social_2 = pd.read_csv('../Ressources/Densité.csv')

technologie_1 = pd.read_csv('../Ressources/Prix_production.csv')

technologie_2 = pd.read_csv('../Ressources/Importation_poulet.csv')

technologie_3 = pd.read_csv('../Ressources/Tendance_elevage.csv')

environnement = pd.read_csv('../Ressources/Emission_CO2.csv')

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">2 - Nettoyage des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.1 - Fichier Dispo</h3>
</div>

In [3]:
#Afficher les différents elements de la colonens Element
print(dispo['Élément'].unique())

['Production' 'Importations - Quantité' 'Variation de stock'
 'Exportations - Quantité' 'Disponibilité intérieure'
 'Aliments pour animaux' 'Semences' 'Pertes' 'Résidus' 'Nourriture'
 'Disponibilité alimentaire en quantité (kg/personne/an)'
 'Disponibilité alimentaire (Kcal/personne/jour)'
 'Disponibilité de protéines en quantité (g/personne/jour)'
 'Disponibilité de matière grasse en quantité (g/personne/jour)'
 'Traitement' 'Autres utilisations (non alimentaire)'
 'Alimentation pour touristes']

In [4]:
#Ne garder que les lignes où 'Produit' vaut 'Viande de Volailles'
dispo = dispo[dispo['Produit'] == 'Viande de Volailles']

In [5]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(dispo.shape[0]))
print("Le tableau comporte {} colonne(s)".format(dispo.shape[1]))

Le tableau comporte 2061 ligne(s)
Le tableau comporte 14 colonne(s)

In [6]:
#Afficher les détails du dataset
print(dispo.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2061 entries, 651 to 176400
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            2061 non-null   object
 1   Domaine                 2061 non-null   object
 2   Code zone               2061 non-null   int64
 3   Zone                    2061 non-null   object
 4   Code Élément            2061 non-null   int64
 5   Élément                 2061 non-null   object
 6   Code Produit            2061 non-null   int64
 7   Produit                 2061 non-null   object
 8   Code année              2061 non-null   int64
 9   Année                   2061 non-null   int64
 10  Unité                   2061 non-null   object
 11  Valeur                  2061 non-null   float64
 12  Symbole                 2061 non-null   object
 13  Description du Symbole  2061 non-null   object
dtypes: float64(1), int64(5), object(8)
memory usage: 241.5+ KB
None

In [7]:
#Afficher les premières lignes
dispo.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.0,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.0,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.0,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.0,S,Données standardisées

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.2 - Fichier Politique</h3>
</div>

In [8]:
#Modifier le dataset pour ne garder que l'année 2017
politique = politique[['Country Name', 'Country Code','2017']]

In [9]:
#Renommer les colonnes 'Country Name' et 'Country Code'
politique = politique.rename(columns={'Country Name': 'Pays', 'Country Code': 'Code Pays'})

In [10]:
#Supprimer les lignes où toutes les valeurs des années sont manquantes
politique = politique.dropna(subset=['2017'], how='all')

In [11]:
#Supprimer les lignes où la valeur de 'Pays' est manquante
politique = politique.dropna(subset=['Pays'])

In [12]:
#Changer les colonnes d'années en une seule colonne 'Année' avec les valeurs correspondantes dans une colonne 'Stability Rank'
politique = politique.melt(id_vars=['Pays', 'Code Pays'], var_name='Année', value_name='Stabilité politique, rang (%)')

In [13]:
#Afficher les détails du dataset
print(politique.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Pays                           205 non-null    object
 1   Code Pays                      205 non-null    object
 2   Année                          205 non-null    object
 3   Stabilité politique, rang (%)  205 non-null    float64
dtypes: float64(1), object(3)
memory usage: 6.5+ KB
None

In [14]:
#Trier les valeurs par 'Pays'
politique = politique.sort_values(by=['Pays'])
politique.reset_index(drop=True, inplace=True)

In [15]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(politique.shape[0]))
print("Le tableau comporte {} colonne(s)".format(politique.shape[1]))

Le tableau comporte 205 ligne(s)
Le tableau comporte 4 colonne(s)

In [16]:
pays = politique[['Pays', 'Code Pays']].copy()

In [17]:
politique = politique.drop(['Pays','Année'], axis=1)

In [18]:
politique.head()

  Code Pays  Stabilité politique, rang (%)
0       AFG                       0.476190
1       ZAF                      34.285713
2       ALB                      59.523811
3       DZA                      15.714286
4       DEU                      65.238098

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Fichier Économique</h3>
</div>

In [19]:
#Modifier le dataset economique pour ne garder que l'année 2017
economique = economique[['Country Name', 'Country Code','2017']]

In [20]:
#Renommer les colonnes 'Country Name' et 'Country Code'
economique = economique.rename(columns={'Country Name': 'Pays', 'Country Code': 'Code Pays'})

In [21]:
#Supprimer les lignes où toutes les valeurs des années sont manquantes
economique = economique.dropna(subset=['2017'], how='all')

In [22]:
#Supprimer les lignes où la valeur de 'Pays' est manquante
economique = economique.dropna(subset=['Pays'])

In [23]:
#Changer les colonnes d'années en une seule colonne 'Année' avec les valeurs correspondantes dans une colonne 'PIB par habitant'
economique = economique.melt(id_vars=['Pays', 'Code Pays'], var_name='Année', value_name='PIB par habitant')

In [24]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(economique.shape[0]))
print("Le tableau comporte {} colonne(s)".format(economique.shape[1]))

Le tableau comporte 245 ligne(s)
Le tableau comporte 4 colonne(s)

In [25]:
#Afficher les détails du dataset
print(economique.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Pays              245 non-null    object
 1   Code Pays         245 non-null    object
 2   Année             245 non-null    object
 3   PIB par habitant  245 non-null    float64
dtypes: float64(1), object(3)
memory usage: 7.8+ KB
None

In [26]:
#Trier les valeurs par 'Pays'
economique = economique.sort_values(by=['Pays'])
economique.reset_index(drop=True, inplace=True)

In [27]:
pays = pd.concat([pays, economique[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [28]:
economique = economique.drop(['Pays','Année'], axis=1)

In [29]:
economique.head()

  Code Pays  PIB par habitant
0       AFG       2952.998916
1       TMN       9422.456730
2       MNA       9401.349906
3       ZAF      14591.436676
4       SSF       4355.799758

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.4 - Fichier Social_1</h3>
</div>

In [30]:
#Modifier le dataset pour ne garder que les colonnes 'Zone', 'Code Zone', 'Année' et 'Valeur' 
social_1 = social_1[['Zone', 'Code zone (ISO3)', 'Année', 'Valeur']]

In [31]:
#Multiplier les valeurs de la colonne 'Valeur' par 1000 pour obtenir la population totale
social_1['Valeur'] = social_1['Valeur'] * 1000

In [32]:
#Renommer les colonnes pour plus de clarté
social_1 = social_1.rename(columns={'Zone': 'Pays', 'Code zone (ISO3)': 'Code Pays', 'Valeur': 'Population totale'})

In [33]:
#Afficher les détails du dataset
print(economique.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code Pays         245 non-null    object
 1   PIB par habitant  245 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.0+ KB
None

In [34]:
#Changer les types de la colonne 'Population totale' in int
social_1['Population totale'] = social_1['Population totale'].astype(int)

In [35]:
#Trier les valeurs par 'Pays'
social_1 = social_1.sort_values(by=['Pays'])
social_1.reset_index(drop=True, inplace=True)

In [36]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(social_1.shape[0]))
print("Le tableau comporte {} colonne(s)".format(social_1.shape[1]))

Le tableau comporte 234 ligne(s)
Le tableau comporte 4 colonne(s)

In [37]:
pays = pd.concat([pays, social_1[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [38]:
social_1 = social_1.drop(['Pays','Année'], axis=1)

In [39]:
social_1.head()

  Code Pays  Population totale
0       AFG           35688935
1       ZAF           57635162
2       ALB            2898242
3       DZA           41689299
4       DEU           83104007

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.5 - Fichier Social_2</h3>
</div>

In [40]:
#Modifier le dataset economique pour ne garder que l'année 2017
social_2 = social_2[['Country Name', 'Country Code','2017']]

In [41]:
#Modifier le dataset economique pour ne garder que l'année 2017
social_2 = social_2[['Country Name', 'Country Code','2017']]

In [42]:
#Renommer les colonnes 'Country Name' et 'Country Code'
social_2 = social_2.rename(columns={'Country Name': 'Pays', 'Country Code': 'Code Pays'})

In [43]:
#Supprimer les lignes où toutes les valeurs des années sont manquantes
social_2 = social_2.dropna(subset=['2017'], how='all')

In [44]:
#Supprimer les lignes où la valeur de 'Pays' est manquante
social_2 = social_2.dropna(subset=['Pays'])

In [45]:
#Changer les colonnes d'années en une seule colonne 'Année' avec les valeurs correspondantes dans une colonne 'PIB par habitant'
social_2 = social_2.melt(id_vars=['Pays', 'Code Pays'], var_name='Année', value_name='Densité (hab/km²)')

In [46]:
#Afficher les détails du dataset
print(social_2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pays               262 non-null    object
 1   Code Pays          262 non-null    object
 2   Année              262 non-null    object
 3   Densité (hab/km²)  262 non-null    float64
dtypes: float64(1), object(3)
memory usage: 8.3+ KB
None

In [47]:
#Trier les valeurs par 'Pays' et 'Année'
social_2 = social_2.sort_values(by=['Pays', 'Année'])
social_2.reset_index(drop=True, inplace=True)

In [48]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(social_2.shape[0]))
print("Le tableau comporte {} colonne(s)".format(social_2.shape[1]))

Le tableau comporte 262 ligne(s)
Le tableau comporte 4 colonne(s)

In [49]:
pays = pd.concat([pays, social_2[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [50]:
social_2 = social_2.drop(['Pays','Année'], axis=1)

In [51]:
social_2.head()

  Code Pays  Densité (hab/km²)
0       AFG          54.718328
1       TMN          64.894356
2       MNA          65.298429
3       ZAF          47.511035
4       SSF          45.244945

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.6 - Fichier Technologie_1</h3>
</div>

In [52]:
#Modifier le dataset pour ne garder que les colonnes 'Zone', 'Code Zone', 'Année' et 'Valeur' 
technologie_1 = technologie_1[['Zone', 'Code zone (ISO3)', 'Année', 'Valeur']]

In [53]:
#Renommer les colonnes pour plus de clarté
technologie_1 = technologie_1.rename(columns={'Zone': 'Pays', 'Code zone (ISO3)': 'Code Pays', 'Valeur': 'Prix de production (USD/tonne)'})

In [54]:
#Ne garder que les lignes où 'Année' est 2017
technologie_1 = technologie_1[technologie_1['Année'] == 2017]

In [55]:
#Afficher les détails du dataset
print(technologie_1.info())

<class 'pandas.core.frame.DataFrame'>
Index: 131 entries, 4 to 713
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Pays                            131 non-null    object
 1   Code Pays                       131 non-null    object
 2   Année                           131 non-null    int64
 3   Prix de production (USD/tonne)  131 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 5.1+ KB
None

In [56]:
#Trier les valeurs par 'Pays' et 'Année'
technologie_1 = technologie_1.sort_values(by=['Pays', 'Année'])
technologie_1.reset_index(drop=True, inplace=True)

In [57]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(technologie_1.shape[0]))
print("Le tableau comporte {} colonne(s)".format(technologie_1.shape[1]))

Le tableau comporte 131 ligne(s)
Le tableau comporte 4 colonne(s)

In [58]:
pays = pd.concat([pays, technologie_1[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [59]:
technologie_1 = technologie_1.drop(['Pays','Année'], axis=1)

In [60]:
technologie_1.head()

  Code Pays  Prix de production (USD/tonne)
0       ZAF                          2015.1
1       DZA                          2180.7
2       DEU                          1459.5
3       ATG                          4402.0
4       SAU                          3464.2

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.7 - Fichier Technologie_2</h3>
</div>

In [61]:
#Modifier le dataset pour ne garder que les colonnes 'Zone', 'Code Zone', 'Année' et 'Valeur' 
technologie_2 = technologie_2[['Zone', 'Code zone (ISO3)', 'Année', 'Valeur']]

In [62]:
#Renommer les colonnes pour plus de clarté
technologie_2 = technologie_2.rename(columns={'Zone': 'Pays', 'Code zone (ISO3)': 'Code Pays', 'Valeur': 'Importation de poulet (tonne)'})

In [63]:
#Ne garder que les lignes où 'Année' est 2017
technologie_2 = technologie_2[technologie_2['Année'] == 2017]

In [64]:
#Afficher les détails du dataset
print(technologie_2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 4 to 1140
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Pays                           191 non-null    object
 1   Code Pays                      191 non-null    object
 2   Année                          191 non-null    int64
 3   Importation de poulet (tonne)  191 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 7.5+ KB
None

In [65]:
#Trier les valeurs par 'Pays' et 'Année'
technologie_2 = technologie_2.sort_values(by=['Pays', 'Année'])
technologie_2.reset_index(drop=True, inplace=True)

In [66]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(technologie_2.shape[0]))
print("Le tableau comporte {} colonne(s)".format(technologie_2.shape[1]))

Le tableau comporte 191 ligne(s)
Le tableau comporte 4 colonne(s)

In [67]:
pays = pd.concat([pays, technologie_2[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [68]:
technologie_2 = technologie_2.drop(['Pays','Année'], axis=1)

In [69]:
technologie_2.head()

  Code Pays  Importation de poulet (tonne)
0       AFG                       28937.00
1       ZAF                      480345.55
2       ALB                       17515.47
3       DZA                           0.40
4       DEU                      474950.63

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.8 - Fichier Technologie_3</h3>
</div>

In [70]:
#Modifier le dataset pour ne garder que les colonnes 'Zone', 'Code Zone', 'Année' et 'Valeur' 
technologie_3 = technologie_3[['Zone', 'Code zone (ISO3)', 'Année', 'Valeur']]

In [71]:
#Renommer les colonnes pour plus de clarté
technologie_3 = technologie_3.rename(columns={'Zone': 'Pays', 'Code zone (ISO3)': 'Code Pays', 'Valeur': '% du total des UGB'})

In [72]:
#Ne garder que les lignes où 'Année' est 2017
technologie_3 = technologie_3[technologie_3['Année'] == 2017]

In [73]:
#Afficher les détails du dataset
print(technologie_3.info())

<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 4 to 1246
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Pays                208 non-null    object
 1   Code Pays           208 non-null    object
 2   Année               208 non-null    int64
 3   % du total des UGB  208 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 8.1+ KB
None

In [74]:
#Trier les valeurs par 'Pays' et 'Année'
technologie_3 = technologie_3.sort_values(by=['Pays', 'Année'])
technologie_3.reset_index(drop=True, inplace=True)

In [75]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(technologie_3.shape[0]))
print("Le tableau comporte {} colonne(s)".format(technologie_3.shape[1]))

Le tableau comporte 208 ligne(s)
Le tableau comporte 4 colonne(s)

In [76]:
pays = pd.concat([pays, technologie_3[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Pays']).reset_index(drop=True)

In [77]:
technologie_3 = technologie_3.drop(['Pays','Année'], axis=1)

In [78]:
technologie_3.head()

  Code Pays  % du total des UGB
0       AFG                2.04
1       ZAF               11.81
2       ALB               10.54
3       DZA               21.13
4       DEU                7.99

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.9 - Fichier Environnement</h3>
</div>

In [79]:
#Modifier le dataset pour ne garder que les colonnes 'Zone', 'Code Zone', 'Année' et 'Valeur' 
environnement = environnement[['Zone', 'Code zone (ISO3)', 'Année', 'Valeur']]

In [80]:
#Renommer les colonnes pour plus de clarté
environnement = environnement.rename(columns={'Zone': 'Pays', 'Code zone (ISO3)': 'Code Pays', 'Valeur': 'Émission de CO2eq (kt)'})

In [81]:
#Ne garder que les lignes où 'Année' est 2017
environnement = environnement[environnement['Année'] == 2017]

In [82]:
#Afficher les détails du dataset
print(environnement.info())

<class 'pandas.core.frame.DataFrame'>
Index: 212 entries, 4 to 1270
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Pays                    212 non-null    object
 1   Code Pays               212 non-null    object
 2   Année                   212 non-null    int64
 3   Émission de CO2eq (kt)  212 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 8.3+ KB
None

In [83]:
#Changer les types de la colonne 'Année' in int
environnement['Année'] = environnement['Année'].astype(int)

In [84]:
#Trier les valeurs par 'Pays' et 'Année'
environnement = environnement.sort_values(by=['Pays', 'Année'])
environnement.reset_index(drop=True, inplace=True)

In [85]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(environnement.shape[0]))
print("Le tableau comporte {} colonne(s)".format(environnement.shape[1]))

Le tableau comporte 212 ligne(s)
Le tableau comporte 4 colonne(s)

In [86]:
pays = pd.concat([pays, environnement[['Pays', 'Code Pays']].copy()]).drop_duplicates().sort_values(by=['Code Pays']).reset_index(drop=True)

In [87]:
environnement = environnement.drop(['Pays','Année'], axis=1)

In [88]:
environnement.head()

  Code Pays  Émission de CO2eq (kt)
0       AFG                 10.0577
1       ZAF                524.6676
2       ALB                 10.4864
3       DZA                454.6895
4       DEU                415.7003

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">3 - Jointure des fichiers et analyse exploratoire</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.1 - Jointure des fichiers</h3>
</div>

In [89]:
#On affiche les doublons de 'Pays' dans le dataframe 'pays'
pays[pays.duplicated(subset=['Pays'], keep=False)]

     Pays Code Pays
44  Chine       CHN
86  Chine      F351

In [90]:
pays = pays[~(pays['Code Pays'] == 'F351')].reset_index(drop=True)
pays[pays.duplicated(subset=['Pays'], keep=False)]

Empty DataFrame
Columns: [Pays, Code Pays]
Index: []

In [91]:
pays[pays.duplicated(subset=['Code Pays'], keep=False)]

                                       Pays Code Pays
30          Bolivie (État plurinational de)       BOL
31                                  Bolivie       BOL
43                      Chine, continentale       CHN
44                                    Chine       CHN
47        Congo, République démocratique du       COD
..                                      ...       ...
298  Venezuela (République bolivarienne du)       VEN
300                       Îles Vierges (EU)       VIR
301                Îles Vierges américaines       VIR
308                                   Yémen       YEM
309                          Yémen, Rép. du       YEM

[62 rows x 2 columns]

In [92]:
doublons_code_pays = ['Bolivie (État plurinational de)','Chine, continentale','Congo, République démocratique du','Congo, République du','Curacao','Îles Caïmans','Tchéquie','Égypte, République arabe d’','Micronésie (États fédérés de)','Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord','Chine, RAS de Hong Kong','Iran (République islamique d\')','République kirghize','Corée, République de','Région administrative spéciale de Macao, Chine','Saint-Martin (fr)','République de Moldova','Îles Mariannes du Nord','Pays-Bas (Royaume des)','Puerto Rico (US)','Corée, République démocratique de','Cisjordanie et Gaza','République fédérale de Somalie','République slovaque','Sint Maarten (Dutch part)','Türkiye','République-Unie de Tanzanie','États-Unis d\'Amérique','Venezuela (République bolivarienne du)','Îles Vierges (EU)','Yémen, Rép. du']

pays = pays[~pays['Pays'].isin(doublons_code_pays)].reset_index(drop=True)

pays[pays.duplicated(subset=['Code Pays'], keep=False)].head()

Empty DataFrame
Columns: [Pays, Code Pays]
Index: []

In [93]:
#Joindre les différents datasets sur la colonne 'Code Pays'
df = pd.merge(pays, politique, on=['Code Pays'], how='outer')
df = pd.merge(df, economique, on=['Code Pays'], how='outer')
df = pd.merge(df, social_1, on=['Code Pays'], how='outer')
df = pd.merge(df, social_2, on=['Code Pays'], how='outer')
df = pd.merge(df, technologie_1, on=['Code Pays'], how='outer')
df = pd.merge(df, technologie_2, on=['Code Pays'], how='outer')
df = pd.merge(df, technologie_3, on=['Code Pays'], how='outer')
df = pd.merge(df, environnement, on=['Code Pays'], how='outer')

In [94]:
df = df.drop(['Code Pays'], axis=1)
df.head()

,Pays,"Stabilité politique, rang (%)",PIB par habitant,Population totale,Densité (hab/km²),Prix de production (USD/tonne),Importation de poulet (tonne),% du total des UGB,Émission de CO2eq (kt)
0,Aruba,95.238098,38558.004558,105731.0,604.083333,NaN,NaN,NaN,0.0000
1,Afghanistan,0.476190,2952.998916,35688935.0,54.718328,NaN,28937.00,2.04,10.0577
2,Angola,30.476191,9042.117129,30234839.0,24.251896,NaN,265888.30,9.19,91.4905
3,Anguilla,NaN,NaN,14425.0,NaN,NaN,NaN,NaN,NaN
4,Albanie,59.523811,14155.853728,2898242.0,104.870693,NaN,17515.47,10.54,10.4864

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.2 - Analyse exploratoire</h3>
</div>

In [95]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(df.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df.shape[1]))

Le tableau comporte 283 ligne(s)
Le tableau comporte 9 colonne(s)

In [96]:
#Vérifier s'il y a des valeurs manquantes
print(df.isnull().sum())

Pays                                1
Stabilité politique, rang (%)      78
PIB par habitant                   38
Population totale                  49
Densité (hab/km²)                  21
Prix de production (USD/tonne)    152
Importation de poulet (tonne)      92
% du total des UGB                 75
Émission de CO2eq (kt)             71
dtype: int64

In [97]:
df = df[~df['Pays'].isnull()]
df = df[~df['Stabilité politique, rang (%)'].isnull()]
df = df[~df['PIB par habitant'].isnull()]
df.loc[df['% du total des UGB'].isnull(), ['% du total des UGB', 'Prix de production (USD/tonne)']] = df.loc[df['% du total des UGB'].isnull(), ['% du total des UGB', 'Prix de production (USD/tonne)']].fillna(0)
df['Prix de production (USD/tonne)'] = df['Prix de production (USD/tonne)'].fillna(df['Prix de production (USD/tonne)'].mean())
df['Importation de poulet (tonne)'] = df['Importation de poulet (tonne)'].fillna(0)
df['Émission de CO2eq (kt)'] = df['Émission de CO2eq (kt)'].fillna(df['Émission de CO2eq (kt)'].mean())
df = df[~(df['Pays'] == 'Kosovo')]
print(df.isnull().sum())

Pays                              0
Stabilité politique, rang (%)     0
PIB par habitant                  0
Population totale                 0
Densité (hab/km²)                 0
Prix de production (USD/tonne)    0
Importation de poulet (tonne)     0
% du total des UGB                0
Émission de CO2eq (kt)            0
dtype: int64

In [98]:
#Décrire les statistiques du dataset
df.describe()

,"Stabilité politique, rang (%)",PIB par habitant,Population totale,Densité (hab/km²),Prix de production (USD/tonne),Importation de poulet (tonne),% du total des UGB,Émission de CO2eq (kt)
count,194.000000,194.000000,1.940000e+02,194.000000,194.000000,194.000000,194.000000,194.000000
mean,49.248895,25102.678060,3.866873e+07,355.058038,2508.408157,59326.243763,19.057268,334.388211
std,28.466196,25829.253000,1.455743e+08,1686.982738,1622.871988,132558.203316,21.724347,1154.016685
min,0.476190,880.993440,1.086900e+04,0.136855,0.000000,0.000000,0.000000,0.000000
25%,24.880953,5704.106099,1.502095e+06,36.435839,1627.250000,634.957500,4.947500,10.507100
50%,48.809525,15480.442736,7.227468e+06,85.626324,2495.544526,9509.625000,11.470000,59.117400
75%,73.690477,35438.472280,2.677462e+07,215.174933,2665.475000,46098.305000,22.580000,261.090300
max,100.000000,133500.278959,1.412355e+09,21051.948052,16516.500000,788451.840000,100.000000,12112.716100

In [99]:
#Afficher les doublons
print(df.duplicated().sum())

0

In [100]:
#Afficher les détails du dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 194 entries, 0 to 282
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Pays                            194 non-null    object
 1   Stabilité politique, rang (%)   194 non-null    float64
 2   PIB par habitant                194 non-null    float64
 3   Population totale               194 non-null    float64
 4   Densité (hab/km²)               194 non-null    float64
 5   Prix de production (USD/tonne)  194 non-null    float64
 6   Importation de poulet (tonne)   194 non-null    float64
 7   % du total des UGB              194 non-null    float64
 8   Émission de CO2eq (kt)          194 non-null    float64
dtypes: float64(8), object(1)
memory usage: 15.2+ KB
None

In [101]:
#Faire la somme de la colonne 'Population totale'
df['Population totale']= df['Population totale'].astype(int)
print("La population étudiée est de {} individus".format(df['Population totale'].sum()))

La population étudiée est de 7501733204 individus

In [102]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} ligne(s)".format(df.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df.shape[1]))

Le tableau comporte 194 ligne(s)
Le tableau comporte 9 colonne(s)

In [103]:
df.head()

,Pays,"Stabilité politique, rang (%)",PIB par habitant,Population totale,Densité (hab/km²),Prix de production (USD/tonne),Importation de poulet (tonne),% du total des UGB,Émission de CO2eq (kt)
0,Aruba,95.238098,38558.004558,105731,604.083333,0.000000,0.00,0.00,0.000000
1,Afghanistan,0.476190,2952.998916,35688935,54.718328,2495.544526,28937.00,2.04,10.057700
2,Angola,30.476191,9042.117129,30234839,24.251896,2495.544526,265888.30,9.19,91.490500
4,Albanie,59.523811,14155.853728,2898242,104.870693,2495.544526,17515.47,10.54,10.486400
5,Andorre,97.142860,63239.657771,73763,156.942553,0.000000,0.00,0.00,334.388211

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">4 - Exportation du fichier</h2>
</div>

In [104]:
#Exporter le dataset nettoyé dans un fichier CSV
df.to_csv('../Ressources/Data.csv', index=False)